export { default as EcrimeContactSection } from "./EcrimeContactSection";
export { default as EcrimeDetailsOfAccusedSection } from "../../EcrimeAccusedDetails/EcrimeAccusedDetails";
export { default as EcrimeFederalEntityDetailsSection } from "./EcrimeFederalEntityDetailsSection";
export { default as EcrimeFormComplainantDetailsSection } from "./EcrimeFormComplainantDetailsSection";
export { default as EcrimeFormComplaintDetailsSection } from "./EcrimeFormComplaintDetailsSection";
export { default as EcrimeFormFinancialLossesSection } from "./EcrimeFormFinancialLossesSection";
export { default as EcrimeFormGovernmentEntityDetailsSection } from "./EcrimeFormGovernmentEntityDetailsSection";
export { default as EcrimeFormPersonalSection } from "./EcrimeFormPersonalSection";
export { default as EcrimePrivateEntityDetailsSection } from "./EcrimePrivateEntityDetailsSection";
