import { EcrimeFormValues } from "../types/EcrimeForm.type";

export const initialValues: EcrimeFormValues = {
  complainantType: "Personal",
  mobileNumber: "",
  email: "",
  details: "",
  relation: "",

  financialLosses: false,
  acceptTerms: false,
  captcha: "",
  accusedList: [],
  hasIdentity: true,
  address: "",
  companyName: "",
  contactNumber: "",
  dateOfBirth: "",
  emiratesId: "",
  entityName: "",
  expiryDate: "",
  firstName: "",
  gender: "",
  hasBranches: null,
  issueDate: "",
  nationality: "",
  ownerName: "",
  passportNo: "",
  surname: "",
  tradingLicenseNumber: "",
  actualLosses: "",
  paymentMethod: [],
  entityAddress: "",
};
