import { EcrimeFormValues } from "../types/EcrimeForm.type";

export const initialValues: EcrimeFormValues = {
  complainantType: "Personal",
  complainantAddress: "",
  mobileNumber: "",
  email: "",
  details: "",
  relation: "",
  file: null,
  financialLosses: false,
  acceptTerms: false,
  captcha: "",
  accusedList: [],
  personal: {
    hasIdentity: true,
    emiratesId: "",
    address: "",
    firstName: "",
    middleName: "",
    surname: "",
    gender: "",
    nationality: "",
    dateOfBirth: "",
    passportNo: "",
    mobileNumber: "",
    landlineNumber: "",
    workNumber: "",
    email: "",
  },
  federalEntityName: "",
  federalContactNumber: "",
  tradingLicenseNumber: "",
  activityType: "",
  issueDate: "",
  companyName: "",
  ownerName: "",
  expiryDate: "",
  hasBranches: false,
  companyContactNumber: "",
};
